[package]
name = "reindeer"
version = "0.1.0"
edition = "2021"

[dependencies]
err-derive = { version = "0.3.1", default-features = false }
zerocopy = { version = "0.7.32", features = ["derive"] }

[features]
default = []
std = ["err-derive/std"]
